### PR TITLE
Add more argument matchers and argument captor

### PR DESCRIPTION
**Pull request by maximkulkin**

### CODE REVIEW

**Comment by kaste** [comment]
Looks great. I think I'll merge this later.

**Comment by maximkulkin** [comment]
I'm not sure about using underscore in comparison/order matcher names (e.g. "eq_", "neq_", "lt_" ...) Those were named so to be consistent with matcher combinators "and_", "or_" and "not_" (non-underscore versions are reserved keywords so you can't use them).

**Comment by kaste** [comment]
Well that's hard to decide. How does it look in real code? Maybe leading underscore looks more familiar? _eq(5) vs. eq_(5). Uppercase? EQ(5)

**Comment by maximkulkin** [comment]
Names starting with underscore by Python's convention is protected/private symbols which those matchers are not. All uppercase is for constants, not functions. That leaves us with names ending with underscore.

The questions was more like do we need underscore at all.

**Comment by kaste** [comment]
Yeah, I'm at the computer now. We should go trailing underscore only when it's needed, that is if it's a reserved word or builtin. So can you please leave the alias `any_`.

**Comment by maximkulkin** [comment]
Removed underscore from comparison/ordering matchers' names.

**Comment by kaste** [comment]
LGTM! Great addition.

**Pull request merged**
