### PR TITLE
Add mention to the original Mockito framework in README

### PR DESCRIPTION
**Pull request by TimvdLippe**

### CODE REVIEW

**Comment by kaste** [comment]
Hey Tim, what brought you here?

**Comment by TimvdLippe** [comment]
I was checking out your projects :)

**Comment by kaste** [comment]
Does mockito Java has a backlink to this python repo as well?

**Comment by TimvdLippe** [comment]
We can probably add a mention here: https://github.com/mockito/mockito/wiki/Mockito-In-Use

**Comment by kaste** [comment]
It's already there https://github.com/mockito/mockito/wiki/Mockito-for-other-languages

🙄

**Comment by TimvdLippe** [comment]
Oh I missed that page. Nice :)

**Pull request merged**
